<?php

/**
 * @file
 * Contains ai_engine_metadata.module functions.
 */

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
// function ai_engine_metadata_field_widget_complete_form_alter(&$field_widget_complete_form, \Drupal\Core\Form\FormStateInterface $form_state, $context) {

function ai_engine_metadata_field_widget_complete_form_alter(&$field_widget_complete_form, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $field_definition = $context['items']->getFieldDefinition();
  ksm($field_widget_complete_form);
  ksm($field_definition->getType());
  if($field_definition->getType() == 'metatag') {
    // If the chat widget is enbabled, then attach the React app and related
    // content to all pages and pass configuration via drupalSettings.
    $config = \Drupal::config('ai_engine_metadata.settings');
    if (!$config->get('enable')) {
      unset($field_widget_complete_form['ai_engine']);
    }
  }
}
