<?php

/**
 * @file
 * Contains ai_engine_chat.module functions.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function ai_engine_chat_page_attachments_alter(array &$attachments) {
  // If the chat widget is enbabled, then attach the React app and related
  // content to all pages and pass configuration via drupalSettings.
  $config = \Drupal::config('ai_engine_chat.settings');
  if ($config->get('enable')) {
    $attachments['#cache']['tags'][] = 'config:ai_engine_chat_settings';
    $attachments['#attached']['drupalSettings']['ai_engine_chat'] = [
      'azure_base_url' => $config->get('azure_base_url'),
      'initial_questions' => json_encode($config->get('prompts')),
      'disclaimer' => $config->get('disclaimer'),
      'footer' => $config->get('footer'),
    ];
    $attachments['#attached']['library'][] = 'ai_engine_chat/chat_widget';
  }
}
